# Generated by Django 2.1.5 on 2019-01-20 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50, verbose_name='数据名')),
                ('file_type', models.IntegerField(default=1, verbose_name='文件类型')),
            ],
            options={
                'verbose_name': '数据信息',
                'verbose_name_plural': '数据信息',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='昵称')),
                ('password', models.CharField(max_length=12, verbose_name='密码')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('email', models.CharField(max_length=30, verbose_name='邮箱')),
                ('image', models.ImageField(default='../static/images/buaa.png', upload_to='image/%Y/%m')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.AddField(
            model_name='data',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.User', verbose_name='所有者'),
        ),
    ]
