# Generated by Django 2.1.5 on 2019-02-22 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20190220_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='file_name',
        ),
        migrations.AddField(
            model_name='data',
            name='file',
            field=models.FileField(default=0, max_length=300, upload_to='goods/%Y/%M', verbose_name='数据文件'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.User', verbose_name='所有者'),
        ),
    ]
