# Generated by Django 2.1.5 on 2019-02-22 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20190222_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='commit_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(default=1, verbose_name='文件类型')),
                ('data_format', models.IntegerField(default=0, verbose_name='数据格式')),
                ('description', models.CharField(max_length=500, verbose_name='上传的附加信息')),
            ],
            options={
                'verbose_name': '数据上传信息',
                'verbose_name_plural': '数据上传信息',
            },
        ),
        migrations.RemoveField(
            model_name='data',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='data',
            name='owner',
        ),
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(max_length=300, upload_to='data/%Y/%M', verbose_name='数据文件'),
        ),
        migrations.AddField(
            model_name='commit_message',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.data', verbose_name='数据文件'),
        ),
        migrations.AddField(
            model_name='commit_message',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.User', verbose_name='所有者'),
        ),
    ]
