# Generated by Django 2.1.5 on 2019-02-22 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20190222_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit_message',
            name='file',
        ),
        migrations.AddField(
            model_name='data',
            name='addition_meg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.commit_message'),
        ),
    ]
