# Generated by Django 2.1.5 on 2019-02-23 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20190222_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='文件上传时间'),
        ),
    ]
