# Generated by Django 2.1.5 on 2019-02-26 22:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_data_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_path', models.CharField(max_length=100, verbose_name='模型文件路径')),
                ('state', models.FloatField(verbose_name='训练进程')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='模型添加时间')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.User', verbose_name='所有者')),
            ],
            options={
                'verbose_name': '模型信息',
                'verbose_name_plural': '模型信息',
            },
        ),
    ]
