# Generated by Django 2.1.5 on 2019-03-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_train_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_model',
            name='type',
            field=models.IntegerField(default=0, verbose_name='模型的类型'),
            preserve_default=False,
        ),
    ]
