# Generated by Django 2.1.5 on 2019-03-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_remove_commit_message_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit_message',
            name='data_format',
        ),
        migrations.AddField(
            model_name='commit_message',
            name='category',
            field=models.IntegerField(default=1, verbose_name='文件类型'),
        ),
    ]
